import Image from "next/image";
import Footer from "./components/footer/Footer";
import MainPage from "./components/mainHome/MainPage";

export const metadata = {
  title: "Grogin Next",
  description: "Generated by create next app",
};

export default function Home() {
  return <div className="wrapper">
    <MainPage/>
  </div>;
}
