import Image from "next/image";

export const metadata = {
  title: "Grogin Next",
  description: "Generated by create next app",
};

export default function Home() {

  return (
   <div className="wrapper">
    home
   </div>
  );
}
